sonar.projectKey=bobapp-front-paul
sonar.organization=PaulBarbeyJunr
sonar.projectName=BobApp Front

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info

sonar.sourceEncoding=UTF-8
